services:
  main_image:
    build:
      context: .
      dockerfile: Dockerfile
    image: mvillasante/huevolizer:latest
    command: bash
    volumes:
      - $PWD:/workdir
  streamlit:
    image: mvillasante/huevolizer:latest
    entrypoint: ["streamlit", "run", "huevolizer/streamlit_app.py", "--server.port=8502", "--server.address=0.0.0.0"]
    ports:
      - "8502:8502"
    volumes:
      - $PWD:/workdir
    restart: always

  develop:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: mvillasante/huevolizer_dev:latest
    command: bash
    volumes:
      - $PWD:/workdir
