name: Push latest
on:
  push:
    branches:
      - develop
jobs:
  build-image:
    name: Build Docker image 🐋
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and export
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: mvillasante/huevolizer:latest
        outputs: type=docker,dest=/tmp/image.tar
    - name: Verifica el formato
      run: docker run mvillasante/huevolizer:latest bash -c "make check & make install"
    - name: Test Python module 🐍
      run: docker run --volume $PWD:/workdir mvillasante/huevolizer:latest make coverage
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@main
      with:
        files: ./coverage.xml
        verbose: true
        token: ${{ secrets.CODECOV }}
    - name: Create/Update tag
      uses: rickstaa/action-create-tag@v1.5.4
      with:
        tag: "latest"
        message: "Latest release"
        force_push_tag: true
