name: Push latest
on:
  push:
    branches:
      - develop
jobs:
  build-image:
    name: Test module 👨🏽❤️🩹
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
    - name: Build Docker image 🐋 with compose 🐳
      uses: hoverkraft-tech/compose-action@main
      env:
       PWD: "${{ github.workspace }}"
    - name: Verifica el formato 🎨
      run: docker compose run main_image bash -c "make check & make install"
    - name: Run tests and coverage 🐍🧪☂️
      run: docker compose run main_image make coverage
    - name: Upload coverage reports to Codecov with GitHub Action ☂️
      uses: codecov/codecov-action@main
      with:
        files: ./coverage.xml
        verbose: true
        token: ${{ secrets.CODECOV }}
    - name: Create/Update tag 🎏
      uses: rickstaa/action-create-tag@main
      with:
        tag: "latest"
        message: "Latest release"
        force_push_tag: true
