name: Push latest
on:
  push:
    branches:
      - develop
jobs:
  build-image:
    name: Build Docker image 🐋
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
    - name: Run docker compose
      uses: hoverkraft-tech/compose-action@v2.0.1
    - name: Verifica el formato
      run: docker compose run mvillasante/huevolizer:latest bash -c "make check & make install"
    - name: Test Python module 🐍
      run: docker compose run mvillasante/huevolizer:latest make coverage
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@main
      with:
        files: ./coverage.xml
        verbose: true
        token: ${{ secrets.CODECOV }}
    - name: Create/Update tag
      uses: rickstaa/action-create-tag@v1.5.4
      with:
        tag: "latest"
        message: "Latest release"
        force_push_tag: true
